# Generated by Django 5.0.4 on 2024-05-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='device_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='last_coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
